package will.test.event.master;

import lombok.Getter;
import will.test.cluster.IMaster;
import will.test.cluster.NodeInfo;
import will.test.event.BaseEvent;

/**
 * This is a message generated by the master to indicate that a node
 * has connected to master node.
 */
@Getter
public class NodeLeaveEvent extends BaseEvent<IMaster> {
    private final NodeInfo node;

    public NodeLeaveEvent(IMaster source, NodeInfo node) {
        super(source);
        this.node = node;
    }
}
